name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: KrakenD Integration
        run: docker-compose -f docker-compose-acc.yml --exit-code-from=krakend-integration up krakend-integration
